name: piano_player
description: Piano player yang menganalisis melodi dan memainkannya otomatis di piano visual.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true